// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apps/basic/search_lab.proto

package pbbasic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SearchLabRequest) Validate() error {
	return nil
}
func (this *SearchLabResponse) Validate() error {
	if this.List != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(this.List))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("List", err)
		}
	}
	return nil
}
func (this *LabInfo) Validate() error {
	return nil
}
