// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/basic/search_equip.proto

package pbbasic

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type SearchEquipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryIdList []int64 `protobuf:"varint,1,rep,name=category_id_list,json=categoryIdList" json:"category_id_list"`
	EquipName      *string `protobuf:"bytes,2,opt,name=equip_name,json=equipName" json:"equip_name"`
	// 分页，第几页
	Pageno *int64 `protobuf:"varint,3,opt,name=pageno,def=1" json:"pageno"`
	// 分页，单页数量
	Count *int64 `protobuf:"varint,4,opt,name=count,def=20" json:"count"`
}

// Default values for SearchEquipRequest fields.
const (
	Default_SearchEquipRequest_Pageno = int64(1)
	Default_SearchEquipRequest_Count  = int64(20)
)

func (x *SearchEquipRequest) Reset() {
	*x = SearchEquipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_search_equip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEquipRequest) ProtoMessage() {}

func (x *SearchEquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_search_equip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEquipRequest.ProtoReflect.Descriptor instead.
func (*SearchEquipRequest) Descriptor() ([]byte, []int) {
	return file_apps_basic_search_equip_proto_rawDescGZIP(), []int{0}
}

func (x *SearchEquipRequest) GetCategoryIdList() []int64 {
	if x != nil {
		return x.CategoryIdList
	}
	return nil
}

func (x *SearchEquipRequest) GetEquipName() string {
	if x != nil && x.EquipName != nil {
		return *x.EquipName
	}
	return ""
}

func (x *SearchEquipRequest) GetPageno() int64 {
	if x != nil && x.Pageno != nil {
		return *x.Pageno
	}
	return Default_SearchEquipRequest_Pageno
}

func (x *SearchEquipRequest) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return Default_SearchEquipRequest_Count
}

type SearchEquipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *int64       `protobuf:"varint,1,opt,name=total" json:"total"`
	List  []*EquipInfo `protobuf:"bytes,2,rep,name=list" json:"list"`
}

func (x *SearchEquipResponse) Reset() {
	*x = SearchEquipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_search_equip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEquipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEquipResponse) ProtoMessage() {}

func (x *SearchEquipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_search_equip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEquipResponse.ProtoReflect.Descriptor instead.
func (*SearchEquipResponse) Descriptor() ([]byte, []int) {
	return file_apps_basic_search_equip_proto_rawDescGZIP(), []int{1}
}

func (x *SearchEquipResponse) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *SearchEquipResponse) GetList() []*EquipInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type EquipInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipId      *string  `protobuf:"bytes,1,opt,name=equip_id,json=equipId" json:"equip_id"`
	EquipName    *string  `protobuf:"bytes,2,opt,name=equip_name,json=equipName" json:"equip_name"`
	CategoryId   *int64   `protobuf:"varint,3,opt,name=category_id,json=categoryId" json:"category_id"`
	CategoryName *string  `protobuf:"bytes,4,opt,name=category_name,json=categoryName" json:"category_name"`
	Description  *string  `protobuf:"bytes,5,opt,name=description" json:"description"`
	Creator      *string  `protobuf:"bytes,6,opt,name=creator" json:"creator"`
	Ctime        *int64   `protobuf:"varint,7,opt,name=ctime" json:"ctime"`
	Model        *string  `protobuf:"bytes,9,opt,name=model" json:"model"`
	Images       []string `protobuf:"bytes,10,rep,name=images" json:"images"`
}

func (x *EquipInfo) Reset() {
	*x = EquipInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_search_equip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipInfo) ProtoMessage() {}

func (x *EquipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_search_equip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipInfo.ProtoReflect.Descriptor instead.
func (*EquipInfo) Descriptor() ([]byte, []int) {
	return file_apps_basic_search_equip_proto_rawDescGZIP(), []int{2}
}

func (x *EquipInfo) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *EquipInfo) GetEquipName() string {
	if x != nil && x.EquipName != nil {
		return *x.EquipName
	}
	return ""
}

func (x *EquipInfo) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *EquipInfo) GetCategoryName() string {
	if x != nil && x.CategoryName != nil {
		return *x.CategoryName
	}
	return ""
}

func (x *EquipInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *EquipInfo) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *EquipInfo) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

func (x *EquipInfo) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *EquipInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_apps_basic_search_equip_proto protoreflect.FileDescriptor

var file_apps_basic_search_equip_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x62, 0x62, 0x61, 0x73, 0x69, 0x63, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x10, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65,
	0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x31, 0x52, 0x06, 0x70, 0x61, 0x67,
	0x65, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x3a, 0x02, 0x32, 0x30, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x53, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x8b, 0x02, 0x0a, 0x09, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x65, 0x69, 0x6d, 0x75, 0x6d, 0x6f, 0x6b, 0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x62, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70,
	0x73, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x61, 0x73, 0x69, 0x63,
}

var (
	file_apps_basic_search_equip_proto_rawDescOnce sync.Once
	file_apps_basic_search_equip_proto_rawDescData = file_apps_basic_search_equip_proto_rawDesc
)

func file_apps_basic_search_equip_proto_rawDescGZIP() []byte {
	file_apps_basic_search_equip_proto_rawDescOnce.Do(func() {
		file_apps_basic_search_equip_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_basic_search_equip_proto_rawDescData)
	})
	return file_apps_basic_search_equip_proto_rawDescData
}

var file_apps_basic_search_equip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_basic_search_equip_proto_goTypes = []interface{}{
	(*SearchEquipRequest)(nil),  // 0: pbbasic.SearchEquipRequest
	(*SearchEquipResponse)(nil), // 1: pbbasic.SearchEquipResponse
	(*EquipInfo)(nil),           // 2: pbbasic.EquipInfo
}
var file_apps_basic_search_equip_proto_depIdxs = []int32{
	2, // 0: pbbasic.SearchEquipResponse.list:type_name -> pbbasic.EquipInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_basic_search_equip_proto_init() }
func file_apps_basic_search_equip_proto_init() {
	if File_apps_basic_search_equip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_basic_search_equip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchEquipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_basic_search_equip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchEquipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_basic_search_equip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_basic_search_equip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_basic_search_equip_proto_goTypes,
		DependencyIndexes: file_apps_basic_search_equip_proto_depIdxs,
		MessageInfos:      file_apps_basic_search_equip_proto_msgTypes,
	}.Build()
	File_apps_basic_search_equip_proto = out.File
	file_apps_basic_search_equip_proto_rawDesc = nil
	file_apps_basic_search_equip_proto_goTypes = nil
	file_apps_basic_search_equip_proto_depIdxs = nil
}
