// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/basic/search_lab.proto

package pbbasic

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type SearchLabRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 分页，第几页
	Pageno *int64 `protobuf:"varint,2,opt,name=pageno,def=1" json:"pageno"`
	// 分页，单页数量
	Count *int64 `protobuf:"varint,3,opt,name=count,def=20" json:"count"`
}

// Default values for SearchLabRequest fields.
const (
	Default_SearchLabRequest_Pageno = int64(1)
	Default_SearchLabRequest_Count  = int64(20)
)

func (x *SearchLabRequest) Reset() {
	*x = SearchLabRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_search_lab_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchLabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLabRequest) ProtoMessage() {}

func (x *SearchLabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_search_lab_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLabRequest.ProtoReflect.Descriptor instead.
func (*SearchLabRequest) Descriptor() ([]byte, []int) {
	return file_apps_basic_search_lab_proto_rawDescGZIP(), []int{0}
}

func (x *SearchLabRequest) GetPageno() int64 {
	if x != nil && x.Pageno != nil {
		return *x.Pageno
	}
	return Default_SearchLabRequest_Pageno
}

func (x *SearchLabRequest) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return Default_SearchLabRequest_Count
}

type SearchLabResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *int64     `protobuf:"varint,1,opt,name=total" json:"total"`
	List  []*LabInfo `protobuf:"bytes,2,rep,name=list" json:"list"`
}

func (x *SearchLabResponse) Reset() {
	*x = SearchLabResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_search_lab_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchLabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLabResponse) ProtoMessage() {}

func (x *SearchLabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_search_lab_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLabResponse.ProtoReflect.Descriptor instead.
func (*SearchLabResponse) Descriptor() ([]byte, []int) {
	return file_apps_basic_search_lab_proto_rawDescGZIP(), []int{1}
}

func (x *SearchLabResponse) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *SearchLabResponse) GetList() []*LabInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type LabInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabCode     *string `protobuf:"bytes,1,opt,name=lab_code,json=labCode" json:"lab_code"`
	LabName     *string `protobuf:"bytes,2,opt,name=lab_name,json=labName" json:"lab_name"`
	Address     *string `protobuf:"bytes,4,opt,name=address" json:"address"`
	Description *string `protobuf:"bytes,5,opt,name=description" json:"description"`
	Creator     *string `protobuf:"bytes,6,opt,name=creator" json:"creator"`
	Ctime       *int64  `protobuf:"varint,7,opt,name=ctime" json:"ctime"`
}

func (x *LabInfo) Reset() {
	*x = LabInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_search_lab_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabInfo) ProtoMessage() {}

func (x *LabInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_search_lab_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabInfo.ProtoReflect.Descriptor instead.
func (*LabInfo) Descriptor() ([]byte, []int) {
	return file_apps_basic_search_lab_proto_rawDescGZIP(), []int{2}
}

func (x *LabInfo) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *LabInfo) GetLabName() string {
	if x != nil && x.LabName != nil {
		return *x.LabName
	}
	return ""
}

func (x *LabInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *LabInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *LabInfo) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *LabInfo) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

var File_apps_basic_search_lab_proto protoreflect.FileDescriptor

var file_apps_basic_search_lab_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x5f, 0x6c, 0x61, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x62, 0x62, 0x61, 0x73, 0x69, 0x63, 0x22, 0x47, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4c, 0x61, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x06, 0x70, 0x61,
	0x67, 0x65, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x31, 0x52, 0x06, 0x70,
	0x61, 0x67, 0x65, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x3a, 0x02, 0x32, 0x30, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x4f, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x61, 0x62, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x4c, 0x61, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0xab, 0x01, 0x0a, 0x07, 0x4c, 0x61, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x3d,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69,
	0x6d, 0x75, 0x6d, 0x6f, 0x6b, 0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69, 0x70, 0x62,
	0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x61, 0x73, 0x69, 0x63,
}

var (
	file_apps_basic_search_lab_proto_rawDescOnce sync.Once
	file_apps_basic_search_lab_proto_rawDescData = file_apps_basic_search_lab_proto_rawDesc
)

func file_apps_basic_search_lab_proto_rawDescGZIP() []byte {
	file_apps_basic_search_lab_proto_rawDescOnce.Do(func() {
		file_apps_basic_search_lab_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_basic_search_lab_proto_rawDescData)
	})
	return file_apps_basic_search_lab_proto_rawDescData
}

var file_apps_basic_search_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_basic_search_lab_proto_goTypes = []interface{}{
	(*SearchLabRequest)(nil),  // 0: pbbasic.SearchLabRequest
	(*SearchLabResponse)(nil), // 1: pbbasic.SearchLabResponse
	(*LabInfo)(nil),           // 2: pbbasic.LabInfo
}
var file_apps_basic_search_lab_proto_depIdxs = []int32{
	2, // 0: pbbasic.SearchLabResponse.list:type_name -> pbbasic.LabInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_basic_search_lab_proto_init() }
func file_apps_basic_search_lab_proto_init() {
	if File_apps_basic_search_lab_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_basic_search_lab_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchLabRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_basic_search_lab_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchLabResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_basic_search_lab_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_basic_search_lab_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_basic_search_lab_proto_goTypes,
		DependencyIndexes: file_apps_basic_search_lab_proto_depIdxs,
		MessageInfos:      file_apps_basic_search_lab_proto_msgTypes,
	}.Build()
	File_apps_basic_search_lab_proto = out.File
	file_apps_basic_search_lab_proto_rawDesc = nil
	file_apps_basic_search_lab_proto_goTypes = nil
	file_apps_basic_search_lab_proto_depIdxs = nil
}
