// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apps/basic/update_equip.proto

package pbbasic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UpdateEquipRequest) Validate() error {
	return nil
}
func (this *UpdateEquipResponse) Validate() error {
	return nil
}
