// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/basic/user_login.proto

package pbbasic

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type UserLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientType *int64  `protobuf:"varint,1,req,name=client_type,json=clientType" json:"client_type"`
	Code       *string `protobuf:"bytes,2,req,name=code" json:"code"`
	Passwd     *string `protobuf:"bytes,3,req,name=passwd" json:"passwd"`
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_user_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_user_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_apps_basic_user_login_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginRequest) GetClientType() int64 {
	if x != nil && x.ClientType != nil {
		return *x.ClientType
	}
	return 0
}

func (x *UserLoginRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *UserLoginRequest) GetPasswd() string {
	if x != nil && x.Passwd != nil {
		return *x.Passwd
	}
	return ""
}

type UserLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginStatus *int64  `protobuf:"varint,1,req,name=login_status,json=loginStatus" json:"login_status"`
	UserName    *string `protobuf:"bytes,2,req,name=user_name,json=userName" json:"user_name"`
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_basic_user_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_basic_user_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_apps_basic_user_login_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginResponse) GetLoginStatus() int64 {
	if x != nil && x.LoginStatus != nil {
		return *x.LoginStatus
	}
	return 0
}

func (x *UserLoginResponse) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

var File_apps_basic_user_login_proto protoreflect.FileDescriptor

var file_apps_basic_user_login_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x62, 0x62, 0x61, 0x73, 0x69, 0x63, 0x22, 0x5f, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x22, 0x53, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x3d, 0x5a, 0x3b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69, 0x6d, 0x75,
	0x6d, 0x6f, 0x6b, 0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69, 0x70, 0x62, 0x6d, 0x73,
	0x2f, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x61, 0x73, 0x69, 0x63,
}

var (
	file_apps_basic_user_login_proto_rawDescOnce sync.Once
	file_apps_basic_user_login_proto_rawDescData = file_apps_basic_user_login_proto_rawDesc
)

func file_apps_basic_user_login_proto_rawDescGZIP() []byte {
	file_apps_basic_user_login_proto_rawDescOnce.Do(func() {
		file_apps_basic_user_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_basic_user_login_proto_rawDescData)
	})
	return file_apps_basic_user_login_proto_rawDescData
}

var file_apps_basic_user_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_basic_user_login_proto_goTypes = []interface{}{
	(*UserLoginRequest)(nil),  // 0: pbbasic.UserLoginRequest
	(*UserLoginResponse)(nil), // 1: pbbasic.UserLoginResponse
}
var file_apps_basic_user_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_basic_user_login_proto_init() }
func file_apps_basic_user_login_proto_init() {
	if File_apps_basic_user_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_basic_user_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_basic_user_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_basic_user_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_basic_user_login_proto_goTypes,
		DependencyIndexes: file_apps_basic_user_login_proto_depIdxs,
		MessageInfos:      file_apps_basic_user_login_proto_msgTypes,
	}.Build()
	File_apps_basic_user_login_proto = out.File
	file_apps_basic_user_login_proto_rawDesc = nil
	file_apps_basic_user_login_proto_goTypes = nil
	file_apps_basic_user_login_proto_depIdxs = nil
}
