// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/bms/cancel_borrow.proto

package pbbms

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type CancelBorrowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BorrowId *string `protobuf:"bytes,1,req,name=borrow_id,json=borrowId" json:"borrow_id"`
	Reason   *string `protobuf:"bytes,2,opt,name=reason" json:"reason"`
}

func (x *CancelBorrowRequest) Reset() {
	*x = CancelBorrowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_cancel_borrow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBorrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBorrowRequest) ProtoMessage() {}

func (x *CancelBorrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_cancel_borrow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBorrowRequest.ProtoReflect.Descriptor instead.
func (*CancelBorrowRequest) Descriptor() ([]byte, []int) {
	return file_apps_bms_cancel_borrow_proto_rawDescGZIP(), []int{0}
}

func (x *CancelBorrowRequest) GetBorrowId() string {
	if x != nil && x.BorrowId != nil {
		return *x.BorrowId
	}
	return ""
}

func (x *CancelBorrowRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CancelBorrowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelBorrowResponse) Reset() {
	*x = CancelBorrowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_cancel_borrow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelBorrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBorrowResponse) ProtoMessage() {}

func (x *CancelBorrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_cancel_borrow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBorrowResponse.ProtoReflect.Descriptor instead.
func (*CancelBorrowResponse) Descriptor() ([]byte, []int) {
	return file_apps_bms_cancel_borrow_proto_rawDescGZIP(), []int{1}
}

var File_apps_bms_cancel_borrow_proto protoreflect.FileDescriptor

var file_apps_bms_cancel_borrow_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x5f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x62, 0x62, 0x6d, 0x73, 0x22, 0x4a, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69, 0x6d, 0x75, 0x6d, 0x6f, 0x6b,
	0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69, 0x70, 0x62, 0x6d, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x70,
	0x62, 0x62, 0x6d, 0x73,
}

var (
	file_apps_bms_cancel_borrow_proto_rawDescOnce sync.Once
	file_apps_bms_cancel_borrow_proto_rawDescData = file_apps_bms_cancel_borrow_proto_rawDesc
)

func file_apps_bms_cancel_borrow_proto_rawDescGZIP() []byte {
	file_apps_bms_cancel_borrow_proto_rawDescOnce.Do(func() {
		file_apps_bms_cancel_borrow_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_bms_cancel_borrow_proto_rawDescData)
	})
	return file_apps_bms_cancel_borrow_proto_rawDescData
}

var file_apps_bms_cancel_borrow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_bms_cancel_borrow_proto_goTypes = []interface{}{
	(*CancelBorrowRequest)(nil),  // 0: pbbms.CancelBorrowRequest
	(*CancelBorrowResponse)(nil), // 1: pbbms.CancelBorrowResponse
}
var file_apps_bms_cancel_borrow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_bms_cancel_borrow_proto_init() }
func file_apps_bms_cancel_borrow_proto_init() {
	if File_apps_bms_cancel_borrow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_bms_cancel_borrow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBorrowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_cancel_borrow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelBorrowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_bms_cancel_borrow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_bms_cancel_borrow_proto_goTypes,
		DependencyIndexes: file_apps_bms_cancel_borrow_proto_depIdxs,
		MessageInfos:      file_apps_bms_cancel_borrow_proto_msgTypes,
	}.Build()
	File_apps_bms_cancel_borrow_proto = out.File
	file_apps_bms_cancel_borrow_proto_rawDesc = nil
	file_apps_bms_cancel_borrow_proto_goTypes = nil
	file_apps_bms_cancel_borrow_proto_depIdxs = nil
}
