// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/bms/create_equip_inv.proto

package pbbms

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type CreateEquipInvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipId     *string `protobuf:"bytes,1,req,name=equip_id,json=equipId" json:"equip_id"`
	LabCode     *string `protobuf:"bytes,2,req,name=lab_code,json=labCode" json:"lab_code"`
	Description *string `protobuf:"bytes,3,req,name=description" json:"description"`
	Count       *int64  `protobuf:"varint,4,req,name=count" json:"count"`
}

func (x *CreateEquipInvRequest) Reset() {
	*x = CreateEquipInvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_create_equip_inv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEquipInvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEquipInvRequest) ProtoMessage() {}

func (x *CreateEquipInvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_create_equip_inv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEquipInvRequest.ProtoReflect.Descriptor instead.
func (*CreateEquipInvRequest) Descriptor() ([]byte, []int) {
	return file_apps_bms_create_equip_inv_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEquipInvRequest) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *CreateEquipInvRequest) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *CreateEquipInvRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateEquipInvRequest) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type CreateEquipInvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateEquipInvResponse) Reset() {
	*x = CreateEquipInvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_create_equip_inv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEquipInvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEquipInvResponse) ProtoMessage() {}

func (x *CreateEquipInvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_create_equip_inv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEquipInvResponse.ProtoReflect.Descriptor instead.
func (*CreateEquipInvResponse) Descriptor() ([]byte, []int) {
	return file_apps_bms_create_equip_inv_proto_rawDescGZIP(), []int{1}
}

var File_apps_bms_create_equip_inv_proto protoreflect.FileDescriptor

var file_apps_bms_create_equip_inv_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x6e, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49,
	0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69, 0x6d, 0x75, 0x6d, 0x6f,
	0x6b, 0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69, 0x70, 0x62, 0x6d, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f,
	0x70, 0x62, 0x62, 0x6d, 0x73,
}

var (
	file_apps_bms_create_equip_inv_proto_rawDescOnce sync.Once
	file_apps_bms_create_equip_inv_proto_rawDescData = file_apps_bms_create_equip_inv_proto_rawDesc
)

func file_apps_bms_create_equip_inv_proto_rawDescGZIP() []byte {
	file_apps_bms_create_equip_inv_proto_rawDescOnce.Do(func() {
		file_apps_bms_create_equip_inv_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_bms_create_equip_inv_proto_rawDescData)
	})
	return file_apps_bms_create_equip_inv_proto_rawDescData
}

var file_apps_bms_create_equip_inv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_bms_create_equip_inv_proto_goTypes = []interface{}{
	(*CreateEquipInvRequest)(nil),  // 0: pbbms.CreateEquipInvRequest
	(*CreateEquipInvResponse)(nil), // 1: pbbms.CreateEquipInvResponse
}
var file_apps_bms_create_equip_inv_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_bms_create_equip_inv_proto_init() }
func file_apps_bms_create_equip_inv_proto_init() {
	if File_apps_bms_create_equip_inv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_bms_create_equip_inv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEquipInvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_create_equip_inv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEquipInvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_bms_create_equip_inv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_bms_create_equip_inv_proto_goTypes,
		DependencyIndexes: file_apps_bms_create_equip_inv_proto_depIdxs,
		MessageInfos:      file_apps_bms_create_equip_inv_proto_msgTypes,
	}.Build()
	File_apps_bms_create_equip_inv_proto = out.File
	file_apps_bms_create_equip_inv_proto_rawDesc = nil
	file_apps_bms_create_equip_inv_proto_goTypes = nil
	file_apps_bms_create_equip_inv_proto_depIdxs = nil
}
