// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/bms/search_borrow_task.proto

package pbbms

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type SearchBorrowTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabCode    *string `protobuf:"bytes,1,opt,name=lab_code,json=labCode" json:"lab_code"`
	EquipId    *string `protobuf:"bytes,2,opt,name=equip_id,json=equipId" json:"equip_id"`
	Operator   *string `protobuf:"bytes,3,opt,name=operator" json:"operator"`
	TaskStatus *int64  `protobuf:"varint,4,opt,name=task_status,json=taskStatus" json:"task_status"`
}

func (x *SearchBorrowTaskRequest) Reset() {
	*x = SearchBorrowTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_borrow_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBorrowTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBorrowTaskRequest) ProtoMessage() {}

func (x *SearchBorrowTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_borrow_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBorrowTaskRequest.ProtoReflect.Descriptor instead.
func (*SearchBorrowTaskRequest) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_borrow_task_proto_rawDescGZIP(), []int{0}
}

func (x *SearchBorrowTaskRequest) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *SearchBorrowTaskRequest) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *SearchBorrowTaskRequest) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *SearchBorrowTaskRequest) GetTaskStatus() int64 {
	if x != nil && x.TaskStatus != nil {
		return *x.TaskStatus
	}
	return 0
}

type SearchBorrowTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *int64          `protobuf:"varint,1,opt,name=total" json:"total"`
	List  *BorrowTaskInfo `protobuf:"bytes,2,req,name=list" json:"list"`
}

func (x *SearchBorrowTaskResponse) Reset() {
	*x = SearchBorrowTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_borrow_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBorrowTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBorrowTaskResponse) ProtoMessage() {}

func (x *SearchBorrowTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_borrow_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBorrowTaskResponse.ProtoReflect.Descriptor instead.
func (*SearchBorrowTaskResponse) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_borrow_task_proto_rawDescGZIP(), []int{1}
}

func (x *SearchBorrowTaskResponse) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *SearchBorrowTaskResponse) GetList() *BorrowTaskInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type BorrowTaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     *string           `protobuf:"bytes,11,req,name=task_id,json=taskId" json:"task_id"`
	EquipId    *string           `protobuf:"bytes,1,req,name=equip_id,json=equipId" json:"equip_id"`
	EquipName  []string          `protobuf:"bytes,2,rep,name=equip_name,json=equipName" json:"equip_name"`
	LabCode    *string           `protobuf:"bytes,3,opt,name=lab_code,json=labCode" json:"lab_code"`
	LabName    *string           `protobuf:"bytes,4,opt,name=lab_name,json=labName" json:"lab_name"`
	BorrowQty  *int64            `protobuf:"varint,5,opt,name=borrow_qty,json=borrowQty" json:"borrow_qty"`
	TaskStatus *int64            `protobuf:"varint,6,opt,name=task_status,json=taskStatus" json:"task_status"`
	Operator   *string           `protobuf:"bytes,7,req,name=operator" json:"operator"`
	Ctime      *int64            `protobuf:"varint,9,opt,name=ctime" json:"ctime"`
	LogList    []*BorrowTaskInfo `protobuf:"bytes,10,rep,name=log_list,json=logList" json:"log_list"`
}

func (x *BorrowTaskInfo) Reset() {
	*x = BorrowTaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_borrow_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowTaskInfo) ProtoMessage() {}

func (x *BorrowTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_borrow_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowTaskInfo.ProtoReflect.Descriptor instead.
func (*BorrowTaskInfo) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_borrow_task_proto_rawDescGZIP(), []int{2}
}

func (x *BorrowTaskInfo) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *BorrowTaskInfo) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *BorrowTaskInfo) GetEquipName() []string {
	if x != nil {
		return x.EquipName
	}
	return nil
}

func (x *BorrowTaskInfo) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *BorrowTaskInfo) GetLabName() string {
	if x != nil && x.LabName != nil {
		return *x.LabName
	}
	return ""
}

func (x *BorrowTaskInfo) GetBorrowQty() int64 {
	if x != nil && x.BorrowQty != nil {
		return *x.BorrowQty
	}
	return 0
}

func (x *BorrowTaskInfo) GetTaskStatus() int64 {
	if x != nil && x.TaskStatus != nil {
		return *x.TaskStatus
	}
	return 0
}

func (x *BorrowTaskInfo) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *BorrowTaskInfo) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

func (x *BorrowTaskInfo) GetLogList() []*BorrowTaskInfo {
	if x != nil {
		return x.LogList
	}
	return nil
}

type BorrowTaskLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskStatus *int64  `protobuf:"varint,1,opt,name=task_status,json=taskStatus" json:"task_status"`
	Operator   *string `protobuf:"bytes,2,req,name=operator" json:"operator"`
	Message    *string `protobuf:"bytes,3,req,name=message" json:"message"`
	Info       *string `protobuf:"bytes,5,req,name=info" json:"info"`
	Ctime      *int64  `protobuf:"varint,4,opt,name=ctime" json:"ctime"`
}

func (x *BorrowTaskLog) Reset() {
	*x = BorrowTaskLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_borrow_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowTaskLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowTaskLog) ProtoMessage() {}

func (x *BorrowTaskLog) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_borrow_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowTaskLog.ProtoReflect.Descriptor instead.
func (*BorrowTaskLog) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_borrow_task_proto_rawDescGZIP(), []int{3}
}

func (x *BorrowTaskLog) GetTaskStatus() int64 {
	if x != nil && x.TaskStatus != nil {
		return *x.TaskStatus
	}
	return 0
}

func (x *BorrowTaskLog) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *BorrowTaskLog) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *BorrowTaskLog) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

func (x *BorrowTaskLog) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

var File_apps_bms_search_borrow_task_proto protoreflect.FileDescriptor

var file_apps_bms_search_borrow_task_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x17, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5b, 0x0a, 0x18, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x62, 0x6d,
	0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xbd, 0x02, 0x0a, 0x0e, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x5f, 0x71, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x51, 0x74,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x2e, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6c,
	0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69, 0x6d, 0x75, 0x6d, 0x6f, 0x6b,
	0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69, 0x70, 0x62, 0x6d, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x70,
	0x62, 0x62, 0x6d, 0x73,
}

var (
	file_apps_bms_search_borrow_task_proto_rawDescOnce sync.Once
	file_apps_bms_search_borrow_task_proto_rawDescData = file_apps_bms_search_borrow_task_proto_rawDesc
)

func file_apps_bms_search_borrow_task_proto_rawDescGZIP() []byte {
	file_apps_bms_search_borrow_task_proto_rawDescOnce.Do(func() {
		file_apps_bms_search_borrow_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_bms_search_borrow_task_proto_rawDescData)
	})
	return file_apps_bms_search_borrow_task_proto_rawDescData
}

var file_apps_bms_search_borrow_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_bms_search_borrow_task_proto_goTypes = []interface{}{
	(*SearchBorrowTaskRequest)(nil),  // 0: pbbms.SearchBorrowTaskRequest
	(*SearchBorrowTaskResponse)(nil), // 1: pbbms.SearchBorrowTaskResponse
	(*BorrowTaskInfo)(nil),           // 2: pbbms.BorrowTaskInfo
	(*BorrowTaskLog)(nil),            // 3: pbbms.BorrowTaskLog
}
var file_apps_bms_search_borrow_task_proto_depIdxs = []int32{
	2, // 0: pbbms.SearchBorrowTaskResponse.list:type_name -> pbbms.BorrowTaskInfo
	2, // 1: pbbms.BorrowTaskInfo.log_list:type_name -> pbbms.BorrowTaskInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_bms_search_borrow_task_proto_init() }
func file_apps_bms_search_borrow_task_proto_init() {
	if File_apps_bms_search_borrow_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_bms_search_borrow_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBorrowTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_borrow_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBorrowTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_borrow_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowTaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_borrow_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowTaskLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_bms_search_borrow_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_bms_search_borrow_task_proto_goTypes,
		DependencyIndexes: file_apps_bms_search_borrow_task_proto_depIdxs,
		MessageInfos:      file_apps_bms_search_borrow_task_proto_msgTypes,
	}.Build()
	File_apps_bms_search_borrow_task_proto = out.File
	file_apps_bms_search_borrow_task_proto_rawDesc = nil
	file_apps_bms_search_borrow_task_proto_goTypes = nil
	file_apps_bms_search_borrow_task_proto_depIdxs = nil
}
