// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/bms/search_inv_transaction.proto

package pbbms

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type SearchInvTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabCode  *string `protobuf:"bytes,1,opt,name=lab_code,json=labCode" json:"lab_code"`
	EquipId  *string `protobuf:"bytes,2,opt,name=equip_id,json=equipId" json:"equip_id"`
	Operator *string `protobuf:"bytes,3,opt,name=operator" json:"operator"`
}

func (x *SearchInvTransactionRequest) Reset() {
	*x = SearchInvTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchInvTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvTransactionRequest) ProtoMessage() {}

func (x *SearchInvTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvTransactionRequest.ProtoReflect.Descriptor instead.
func (*SearchInvTransactionRequest) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *SearchInvTransactionRequest) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *SearchInvTransactionRequest) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *SearchInvTransactionRequest) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

type SearchInvTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *int64          `protobuf:"varint,1,opt,name=total" json:"total"`
	List  *InvTransaction `protobuf:"bytes,2,req,name=list" json:"list"`
}

func (x *SearchInvTransactionResponse) Reset() {
	*x = SearchInvTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchInvTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvTransactionResponse) ProtoMessage() {}

func (x *SearchInvTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvTransactionResponse.ProtoReflect.Descriptor instead.
func (*SearchInvTransactionResponse) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *SearchInvTransactionResponse) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *SearchInvTransactionResponse) GetList() *InvTransaction {
	if x != nil {
		return x.List
	}
	return nil
}

type InvTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId *string  `protobuf:"bytes,1,req,name=transaction_id,json=transactionId" json:"transaction_id"`
	SheetId       *string  `protobuf:"bytes,2,req,name=sheet_id,json=sheetId" json:"sheet_id"`
	EquipId       *string  `protobuf:"bytes,3,req,name=equip_id,json=equipId" json:"equip_id"`
	EquipName     []string `protobuf:"bytes,4,rep,name=equip_name,json=equipName" json:"equip_name"`
	LabCode       *string  `protobuf:"bytes,5,opt,name=lab_code,json=labCode" json:"lab_code"`
	LabName       *string  `protobuf:"bytes,6,opt,name=lab_name,json=labName" json:"lab_name"`
	Operator      *string  `protobuf:"bytes,7,opt,name=operator" json:"operator"`
	Remark        *string  `protobuf:"bytes,8,opt,name=remark" json:"remark"`
	AvailQty      *int64   `protobuf:"varint,13,opt,name=avail_qty,json=availQty" json:"avail_qty"`
	OpQty         *int64   `protobuf:"varint,9,opt,name=op_qty,json=opQty" json:"op_qty"`
	TransType     *int64   `protobuf:"varint,10,opt,name=trans_type,json=transType" json:"trans_type"`
	SheetType     *int64   `protobuf:"varint,11,opt,name=sheet_type,json=sheetType" json:"sheet_type"`
	Ctime         *int64   `protobuf:"varint,12,opt,name=ctime" json:"ctime"`
}

func (x *InvTransaction) Reset() {
	*x = InvTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvTransaction) ProtoMessage() {}

func (x *InvTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvTransaction.ProtoReflect.Descriptor instead.
func (*InvTransaction) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *InvTransaction) GetTransactionId() string {
	if x != nil && x.TransactionId != nil {
		return *x.TransactionId
	}
	return ""
}

func (x *InvTransaction) GetSheetId() string {
	if x != nil && x.SheetId != nil {
		return *x.SheetId
	}
	return ""
}

func (x *InvTransaction) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *InvTransaction) GetEquipName() []string {
	if x != nil {
		return x.EquipName
	}
	return nil
}

func (x *InvTransaction) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *InvTransaction) GetLabName() string {
	if x != nil && x.LabName != nil {
		return *x.LabName
	}
	return ""
}

func (x *InvTransaction) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *InvTransaction) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *InvTransaction) GetAvailQty() int64 {
	if x != nil && x.AvailQty != nil {
		return *x.AvailQty
	}
	return 0
}

func (x *InvTransaction) GetOpQty() int64 {
	if x != nil && x.OpQty != nil {
		return *x.OpQty
	}
	return 0
}

func (x *InvTransaction) GetTransType() int64 {
	if x != nil && x.TransType != nil {
		return *x.TransType
	}
	return 0
}

func (x *InvTransaction) GetSheetType() int64 {
	if x != nil && x.SheetType != nil {
		return *x.SheetType
	}
	return 0
}

func (x *InvTransaction) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

var File_apps_bms_search_inv_transaction_proto protoreflect.FileDescriptor

var file_apps_bms_search_inv_transaction_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x69, 0x6e, 0x76, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x22, 0x6f,
	0x0a, 0x1b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6e, 0x76, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x5f, 0x0a, 0x1c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6e, 0x76, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x2e, 0x49, 0x6e, 0x76, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0xfe, 0x02, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68,
	0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x73, 0x68,
	0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61,
	0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61,
	0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x51, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x70, 0x5f, 0x71, 0x74, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x70, 0x51, 0x74, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x68, 0x65, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x68, 0x65, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x74, 0x69, 0x6d,
	0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x65, 0x69, 0x6d, 0x75, 0x6d, 0x6f, 0x6b, 0x65, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x62, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70,
	0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x6d, 0x73,
}

var (
	file_apps_bms_search_inv_transaction_proto_rawDescOnce sync.Once
	file_apps_bms_search_inv_transaction_proto_rawDescData = file_apps_bms_search_inv_transaction_proto_rawDesc
)

func file_apps_bms_search_inv_transaction_proto_rawDescGZIP() []byte {
	file_apps_bms_search_inv_transaction_proto_rawDescOnce.Do(func() {
		file_apps_bms_search_inv_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_bms_search_inv_transaction_proto_rawDescData)
	})
	return file_apps_bms_search_inv_transaction_proto_rawDescData
}

var file_apps_bms_search_inv_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_bms_search_inv_transaction_proto_goTypes = []interface{}{
	(*SearchInvTransactionRequest)(nil),  // 0: pbbms.SearchInvTransactionRequest
	(*SearchInvTransactionResponse)(nil), // 1: pbbms.SearchInvTransactionResponse
	(*InvTransaction)(nil),               // 2: pbbms.InvTransaction
}
var file_apps_bms_search_inv_transaction_proto_depIdxs = []int32{
	2, // 0: pbbms.SearchInvTransactionResponse.list:type_name -> pbbms.InvTransaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_bms_search_inv_transaction_proto_init() }
func file_apps_bms_search_inv_transaction_proto_init() {
	if File_apps_bms_search_inv_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_bms_search_inv_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchInvTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_inv_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchInvTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_inv_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_bms_search_inv_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_bms_search_inv_transaction_proto_goTypes,
		DependencyIndexes: file_apps_bms_search_inv_transaction_proto_depIdxs,
		MessageInfos:      file_apps_bms_search_inv_transaction_proto_msgTypes,
	}.Build()
	File_apps_bms_search_inv_transaction_proto = out.File
	file_apps_bms_search_inv_transaction_proto_rawDesc = nil
	file_apps_bms_search_inv_transaction_proto_goTypes = nil
	file_apps_bms_search_inv_transaction_proto_depIdxs = nil
}
