// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apps/bms/search_borrow_task.proto

package pbbms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SearchBorrowTaskRequest) Validate() error {
	return nil
}
func (this *SearchBorrowTaskResponse) Validate() error {
	if this.List != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(this.List))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("List", err)
		}
	}
	return nil
}
func (this *BorrowTaskInfo) Validate() error {
	for _, item := range this.LogList {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LogList", err)
		}
	}
	return nil
}
func (this *BorrowTaskLog) Validate() error {
	return nil
}
