// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: apps/bms/search_inv_task.proto

package pbbms

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// POST
type SearchInvTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabCode *string `protobuf:"bytes,1,opt,name=lab_code,json=labCode" json:"lab_code"`
	EquipId *string `protobuf:"bytes,2,opt,name=equip_id,json=equipId" json:"equip_id"`
}

func (x *SearchInvTaskRequest) Reset() {
	*x = SearchInvTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchInvTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvTaskRequest) ProtoMessage() {}

func (x *SearchInvTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvTaskRequest.ProtoReflect.Descriptor instead.
func (*SearchInvTaskRequest) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_task_proto_rawDescGZIP(), []int{0}
}

func (x *SearchInvTaskRequest) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *SearchInvTaskRequest) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

type SearchInvTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total *int64       `protobuf:"varint,1,opt,name=total" json:"total"`
	List  *InvTaskInfo `protobuf:"bytes,2,req,name=list" json:"list"`
}

func (x *SearchInvTaskResponse) Reset() {
	*x = SearchInvTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchInvTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvTaskResponse) ProtoMessage() {}

func (x *SearchInvTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvTaskResponse.ProtoReflect.Descriptor instead.
func (*SearchInvTaskResponse) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_task_proto_rawDescGZIP(), []int{1}
}

func (x *SearchInvTaskResponse) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *SearchInvTaskResponse) GetList() *InvTaskInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type InvTaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId          *string       `protobuf:"bytes,11,req,name=task_id,json=taskId" json:"task_id"`
	EquipId         *string       `protobuf:"bytes,1,req,name=equip_id,json=equipId" json:"equip_id"`
	EquipName       []string      `protobuf:"bytes,2,rep,name=equip_name,json=equipName" json:"equip_name"`
	LabCode         *string       `protobuf:"bytes,3,opt,name=lab_code,json=labCode" json:"lab_code"`
	LabName         *string       `protobuf:"bytes,4,opt,name=lab_name,json=labName" json:"lab_name"`
	TotalQty        *int64        `protobuf:"varint,5,opt,name=total_qty,json=totalQty" json:"total_qty"`
	AvailableQty    *int64        `protobuf:"varint,6,opt,name=available_qty,json=availableQty" json:"available_qty"`
	BorrowedQty     *int64        `protobuf:"varint,7,opt,name=borrowed_qty,json=borrowedQty" json:"borrowed_qty"`
	PreAllocatedQty *int64        `protobuf:"varint,8,opt,name=pre_allocated_qty,json=preAllocatedQty" json:"pre_allocated_qty"`
	ReservedQty     *int64        `protobuf:"varint,9,opt,name=reserved_qty,json=reservedQty" json:"reserved_qty"`
	LogList         []*InvTaskLog `protobuf:"bytes,10,rep,name=log_list,json=logList" json:"log_list"`
}

func (x *InvTaskInfo) Reset() {
	*x = InvTaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvTaskInfo) ProtoMessage() {}

func (x *InvTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvTaskInfo.ProtoReflect.Descriptor instead.
func (*InvTaskInfo) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_task_proto_rawDescGZIP(), []int{2}
}

func (x *InvTaskInfo) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *InvTaskInfo) GetEquipId() string {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return ""
}

func (x *InvTaskInfo) GetEquipName() []string {
	if x != nil {
		return x.EquipName
	}
	return nil
}

func (x *InvTaskInfo) GetLabCode() string {
	if x != nil && x.LabCode != nil {
		return *x.LabCode
	}
	return ""
}

func (x *InvTaskInfo) GetLabName() string {
	if x != nil && x.LabName != nil {
		return *x.LabName
	}
	return ""
}

func (x *InvTaskInfo) GetTotalQty() int64 {
	if x != nil && x.TotalQty != nil {
		return *x.TotalQty
	}
	return 0
}

func (x *InvTaskInfo) GetAvailableQty() int64 {
	if x != nil && x.AvailableQty != nil {
		return *x.AvailableQty
	}
	return 0
}

func (x *InvTaskInfo) GetBorrowedQty() int64 {
	if x != nil && x.BorrowedQty != nil {
		return *x.BorrowedQty
	}
	return 0
}

func (x *InvTaskInfo) GetPreAllocatedQty() int64 {
	if x != nil && x.PreAllocatedQty != nil {
		return *x.PreAllocatedQty
	}
	return 0
}

func (x *InvTaskInfo) GetReservedQty() int64 {
	if x != nil && x.ReservedQty != nil {
		return *x.ReservedQty
	}
	return 0
}

func (x *InvTaskInfo) GetLogList() []*InvTaskLog {
	if x != nil {
		return x.LogList
	}
	return nil
}

type InvTaskLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskStatus *int64  `protobuf:"varint,1,opt,name=task_status,json=taskStatus" json:"task_status"`
	Operator   *string `protobuf:"bytes,2,req,name=operator" json:"operator"`
	Message    *string `protobuf:"bytes,3,req,name=message" json:"message"`
	Info       *string `protobuf:"bytes,5,req,name=info" json:"info"`
	Ctime      *int64  `protobuf:"varint,4,opt,name=ctime" json:"ctime"`
}

func (x *InvTaskLog) Reset() {
	*x = InvTaskLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_bms_search_inv_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvTaskLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvTaskLog) ProtoMessage() {}

func (x *InvTaskLog) ProtoReflect() protoreflect.Message {
	mi := &file_apps_bms_search_inv_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvTaskLog.ProtoReflect.Descriptor instead.
func (*InvTaskLog) Descriptor() ([]byte, []int) {
	return file_apps_bms_search_inv_task_proto_rawDescGZIP(), []int{3}
}

func (x *InvTaskLog) GetTaskStatus() int64 {
	if x != nil && x.TaskStatus != nil {
		return *x.TaskStatus
	}
	return 0
}

func (x *InvTaskLog) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *InvTaskLog) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *InvTaskLog) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

func (x *InvTaskLog) GetCtime() int64 {
	if x != nil && x.Ctime != nil {
		return *x.Ctime
	}
	return 0
}

var File_apps_bms_search_inv_task_proto protoreflect.FileDescriptor

var file_apps_bms_search_inv_task_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x5f, 0x69, 0x6e, 0x76, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x22, 0x4c, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x49, 0x6e, 0x76, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49,
	0x6e, 0x76, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x62, 0x6d, 0x73, 0x2e, 0x49, 0x6e, 0x76, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xf8, 0x02, 0x0a,
	0x0b, 0x49, 0x6e, 0x76, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61,
	0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61,
	0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x71,
	0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x51,
	0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x71, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x51, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x64, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x62,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x72,
	0x65, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x71, 0x74, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x72, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x08, 0x6c, 0x6f, 0x67,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x62, 0x6d, 0x73, 0x2e, 0x49, 0x6e, 0x76, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x52, 0x07,
	0x6c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x54,
	0x61, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x69, 0x6d, 0x75, 0x6d, 0x6f, 0x6b, 0x65, 0x2f,
	0x6c, 0x61, 0x62, 0x65, 0x71, 0x75, 0x69, 0x70, 0x62, 0x6d, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x5f,
	0x69, 0x64, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x62, 0x6d, 0x73, 0x2f, 0x70, 0x62, 0x62,
	0x6d, 0x73,
}

var (
	file_apps_bms_search_inv_task_proto_rawDescOnce sync.Once
	file_apps_bms_search_inv_task_proto_rawDescData = file_apps_bms_search_inv_task_proto_rawDesc
)

func file_apps_bms_search_inv_task_proto_rawDescGZIP() []byte {
	file_apps_bms_search_inv_task_proto_rawDescOnce.Do(func() {
		file_apps_bms_search_inv_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_bms_search_inv_task_proto_rawDescData)
	})
	return file_apps_bms_search_inv_task_proto_rawDescData
}

var file_apps_bms_search_inv_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_bms_search_inv_task_proto_goTypes = []interface{}{
	(*SearchInvTaskRequest)(nil),  // 0: pbbms.SearchInvTaskRequest
	(*SearchInvTaskResponse)(nil), // 1: pbbms.SearchInvTaskResponse
	(*InvTaskInfo)(nil),           // 2: pbbms.InvTaskInfo
	(*InvTaskLog)(nil),            // 3: pbbms.InvTaskLog
}
var file_apps_bms_search_inv_task_proto_depIdxs = []int32{
	2, // 0: pbbms.SearchInvTaskResponse.list:type_name -> pbbms.InvTaskInfo
	3, // 1: pbbms.InvTaskInfo.log_list:type_name -> pbbms.InvTaskLog
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_bms_search_inv_task_proto_init() }
func file_apps_bms_search_inv_task_proto_init() {
	if File_apps_bms_search_inv_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_bms_search_inv_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchInvTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_inv_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchInvTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_inv_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvTaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_bms_search_inv_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvTaskLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_bms_search_inv_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_bms_search_inv_task_proto_goTypes,
		DependencyIndexes: file_apps_bms_search_inv_task_proto_depIdxs,
		MessageInfos:      file_apps_bms_search_inv_task_proto_msgTypes,
	}.Build()
	File_apps_bms_search_inv_task_proto = out.File
	file_apps_bms_search_inv_task_proto_rawDesc = nil
	file_apps_bms_search_inv_task_proto_goTypes = nil
	file_apps_bms_search_inv_task_proto_depIdxs = nil
}
