// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apps/bms/search_equip_inv.proto

package pbbms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SearchEquipRequest) Validate() error {
	return nil
}
func (this *SearchEquipResponse) Validate() error {
	for _, item := range this.List {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(&(*(item))); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("List", err)
		}
	}
	return nil
}
func (this *EquipInvInfo) Validate() error {
	return nil
}
