// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: apps/bms/take_borrow.proto

package pbbms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *TaskBorrowRequest) Validate() error {
	return nil
}
func (this *TakeBorrowResponse) Validate() error {
	return nil
}
